### ISSUE TITLE
SHOP_HANDLER_PAYMENT value?

### ISSUE THREAD

**Issue by christaggart** [readevalprint/cartridge-stripe#1]
This looks great, but what do we need to set the SHOP_HANDLER_PAYMENT value to something? The default doesn't actually do anything, and nothing makes its way into Stripe.

**Comment by readevalprint** [comment]
Right, it should be set to `SHOP_HANDLER_PAYMENT = "cartridge_stripe.payment_handler"`

**Comment by readevalprint** [comment]
I'll add that to the docs

**Comment by christaggart** [comment]
Awesome, thanks. Now that that's in place though, i'm wondering if there's anything else I'm missing. When it gets to the page where the credit card values are posted, I get the following exception:

Request Method: POST
Request URL:    http://127.0.0.1:8000/shop/checkout/
Django Version: 1.4.1
Exception Type: KeyError
Exception Value:  
'stripe_token'

It doesn't look like stripe_token is being added to the POST? Is there something else I might be missing?

**Comment by readevalprint** [comment]
If you have customized the `shop/checkout.html` you will have to integrate the changes from here: https://github.com/readevalprint/cartridge-stripe/blob/master/cartridge_stripe/templates/shop/checkout.html 

and if you could paste the whole traceback in a gist too...

**Comment by christaggart** [comment]
Fresh install of mezzanine and cartridge, checkout.html is untouched. 

Traceback: https://gist.github.com/3677737

Update: From what I can tell, its not actually using the provided form for some reason. DjDt shows its using cartridge.shop.forms.OrderForm instead of cartridge_stripe.forms.OrderForm on the billing details page.

Solved. Didn't notice the SHOP_CHECKOUT_FORM_CLASS variable in settings.py (new to cartridge) had to be set to 'cartridge_stripe.forms.OrderForm'. Works great, thanks so much!

**Comment by readevalprint** [comment]
Good find! thanks for reporting back what it was
