### ISSUE TITLE
'NoneType' object has no attribute 'extend' on Cartridge 0.6 and Django 1.4.2

### ISSUE THREAD

**Issue by christaggart** [readevalprint/cartridge-stripe#2]
Looking into why exactly, but my suspicion is something has changed in the OrderForm.

Error during template rendering

In template /.../.virtualenvs/rrhq/lib/python2.7/site-packages/cartridge/shop/templates/shop/payment.html, error at line 7
'NoneType' object has no attribute 'extend'
1   {% extends "shop/checkout.html" %}
2   {% load i18n %}
3  
4   {% block fields %}
5   {% if request.cart.has_items %}
6   {% include "shop/includes/payment_fields.html" %}
7   {{ form.other_fields.as_ul }}
8   {% endif %}
9   {% endblock %}
10

**Comment by christaggart** [comment]
Remember to ensure that checkout.html is being overridden or override it in your your templates directory. Fixed.

**Comment by readevalprint** [comment]
Glad you got it all solved!
