### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by pageworthy** [readevalprint/cartridge-stripe#3]
Running the pip install after installing django-zebra breaks for me. It gave me the following error.

**Comment by pageworthy** [comment]
Sorry, messed that up. The error was:

long_description=open('README.rst').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

I was able to install manually however and so I'll finish the install and check it out. Thanks for this!

**Comment by pageworthy** [comment]
Just trying to get this installed I've had a couple of issues getting test payments to work. Just a note that you do have to install the python stripe module in order for everything to work. I didn't see anything about it in this or django-zebra. Finally I have it running it seems but I get an error on the final checkout that I have not set an API key for Stripe. I have the STRIPE_SECRET and STRIPE_PUBLISHABLE set in my settings.py. Is there somewhere else I need to set my API key?

**Comment by readevalprint** [comment]
yeah, the python stripe module is a requirement of django-zebra. Can you paste the exact error message?

**Comment by pageworthy** [comment]
AuthenticationError at /shop/checkout/
No API key provided. (HINT: set your API key using "stripe.api_key = <API-KEY>"). You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.

**Comment by readevalprint** [comment]
hmm without the full stack trace it's hard to tell, did you add `INSTALLED_APPS += ("zebra",)`

**Comment by pageworthy** [comment]
I had it just as another entry in installed apps but I've taken it out and added it like that now. Still gives the same error. I'll try a few other things. Must be something with my environment perhaps.

**Comment by pageworthy** [comment]
If I put in in Dpaste would that help? I'm just not catching what I'm doing wrong.

**Comment by readevalprint** [comment]
it should be fine to paste it here, just use triple backticks to quote the block.

**Comment by pageworthy** [comment]
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/shop/checkout/

Django Version: 1.4.3
Python Version: 2.6.6
Installed Applications:
['mezzanine.boot',
 'skin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.redirects',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'cartridge_stripe',
 'cartridge.shop',
 'mezzanine.conf',
 'mezzanine.core',
 'mezzanine.generic',
 'mezzanine.blog',
 'mezzanine.forms',
 'mezzanine.pages',
 'mezzanine.galleries',
 'mezzanine.twitter',
 'mezzanine.accounts',
 'zebra',
 'django_extensions',
 'filebrowser_safe',
 'south',
 'grappelli_safe',
 'django.contrib.admin',
 'django.contrib.comments']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'cartridge.shop.middleware.ShopMiddleware',
 'mezzanine.core.request.CurrentRequestMiddleware',
 'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 'mezzanine.core.middleware.TemplateForHostMiddleware',
 'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 'mezzanine.pages.middleware.PageMiddleware']


Traceback:
File "/Users/neum/env/cartridge/lib/python2.6/site-packages/django/core/handlers/base.py" in get_response
  105.                         response = middleware_method(request, callback, callback_args, callback_kwargs)
File "/Users/neum/env/cartridge/lib/python2.6/site-packages/mezzanine/pages/middleware.py" in process_view
  64.         response = view_func(request, *view_args, **view_kwargs)
File "/Users/neum/env/cartridge/lib/python2.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  89.         response = view_func(request, *args, **kwargs)
File "/Users/neum/env/cartridge/lib/python2.6/site-packages/cartridge/shop/views.py" in checkout_steps
  229.                     transaction_id = payment_handler(request, form, order)
File "/Users/neum/Documents/code/cartridge/rhs/apps/cartridge_stripe/__init__.py" in payment_handler
  14.                                       description=order)
File "/Users/neum/Documents/code/cartridge/rhs/apps/stripe/__init__.py" in create
  673.     response, api_key = requestor.request('post', url, params)
File "/Users/neum/Documents/code/cartridge/rhs/apps/stripe/__init__.py" in request
  224.     rbody, rcode, my_api_key = self.request_raw(meth, url, params)
File "/Users/neum/Documents/code/cartridge/rhs/apps/stripe/__init__.py" in request_raw
  249.       raise AuthenticationError('No API key provided. (HINT: set your API key using "stripe.api_key = <API-KEY>"). You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.')

Exception Type: AuthenticationError at /shop/checkout/
Exception Value: No API key provided. (HINT: set your API key using "stripe.api_key = <API-KEY>"). You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
```

**Comment by readevalprint** [comment]
So I'm going to update this with the latest code I used in production.

**Comment by pageworthy** [comment]
That would be great. I've tried installing into a new environment, making sure I follow each step exactly and I'm still getting the same error.

**Comment by readevalprint** [comment]
Ok it's pushed, have you tried `ZEBRA_ENABLE_APP = True` ?

**Comment by pageworthy** [comment]
Can you tell me your Stripe API version? I've redone everything again and I still get the same issue. But its been a while since zebra was updated and the only thing I can see that might be breaking this is my account (set up yesterday) is using a newer version of the API that breaks things.

**Comment by derryspann** [comment]
I was having similar issues with installing cartridge-stripe to my cartridge shop local test site.
At first I was receiving errors saying "ImportError: No module named cartridge_stripe"...This was very confusing after i repeatedly ran the " pip install cartridge-stripe " within terminal. 

So I investigated the issue and found that Pip was not piping Cartridge in the proper virtual env location i have set on my machine.

My solution: Git clone of cartridge-stripe to my machine and paste it into the proper root site package installation.
On my machine it would be:
\Users\hyperking.virtualenvs\pythonapps\lib\python2.7\site-packages\cartridge-stripe

After doing this and carefully following all instructions on the Cartridge-Stripe readme, I was able to process card payments via stripe.

**NOTE** issues i found were:
1. the git clone downloaded directory is named "Cartridge-Stripe". This is problematic and will cause installer to break!  copy the folder named "cartridge_stripe" to the root site packages directory to make this work.
1. There isn't any sort of whereabouts that verify Stripe is being used "Out of the Box" during checkout..not really an issue, but would help to have an admin tab area named "Payments" with the Stripe Test and Live production keys. along with a graphic on the checkout page stating "Your Safely using Stripe Payment Gateway".

Thanks for providing this functional module for cartridge.

**Comment by readevalprint** [comment]
@hyperking that is strange that it is cloning it to "Cartridge-Stripe", @pageworthy are you still having this issue?

**Comment by pageworthy** [comment]
No, I got it working. I was never able to install it with pip. I also tried running setup.py and it installed but the template files were not copied over for some reason. Instead, I simply copied the app directly onto my python path on the server and it works great.

**Comment by readevalprint** [comment]
That's great to hear! Others have had issues installing it with pip as well, I'll check it over again.
