### ISSUE TITLE
cartridge-stripe not passing stripe_token in /shop/checkout/

### ISSUE THREAD

**Issue by robline** [readevalprint/cartridge-stripe#4]
I started over with a clean virtualenv and installed zebra, cartridge-stripe, and then cartridge. Changed the settings.py file with my stripe dev tokens, then fired up the vanilla install.  When I add a red pony to the cart and checkout, I get the errors below on the Payment Details template:

```
(Hidden field last_4_digits) This field is required.
(Hidden field stripe_token) This field is required.
```

**Comment by readevalprint** [comment]
Ok try `pip install cartridge_stripe` again. I've updated the template for Django 1.5 and added it to the MANIFEST. It wasn't your fault.

Note: Make sure `cartridge_stripe` is above `cartridge.shop` in `INSTALLED_APPS` and `zebra` is last.

**Comment by robline** [comment]
Excellent!  Tested it and it works great in Django 1.5.1.
